language: cpp
script: cmake . && cmake --build . && ./runTests
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="export CC=gcc-8"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="export CC=clang-6.0"

    - os: windows
      addons:
        chocolatey:
          packages:
            mingw
      script: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" . && cmake --build . && .\runTests

before_install:
  - eval "${MATRIX_EVAL}"